import { internalMutation, mutation, query } from "./_generated/server.js";
import { v } from "convex/values";

export const enqueue = mutation({ args: { scanId: v.id("scans"), type: v.string(), signature: v.string() }, handler: (ctx, args) => ctx.db.insert("jobs", { ...args, status: "QUEUED", attempt: 0, availableAt: Date.now() }) });
export const pending = query({ args: {}, handler: (ctx) => ctx.db.query("jobs").withIndex("by_status_available", (q) => q.eq("status", "QUEUED")).take(100) });
export const claim = mutation({ args: { jobId: v.id("jobs"), workerId: v.string(), leaseMs: v.number() }, handler: async (ctx, args) => { const job = await ctx.db.get(args.jobId); const now = Date.now(); if (job === null || job.status !== "QUEUED" || job.availableAt > now) return false; await ctx.db.patch(args.jobId, { status: "RUNNING", attempt: job.attempt + 1, leaseOwner: args.workerId, leaseExpiresAt: now + Math.min(args.leaseMs, 120_000), heartbeatAt: now }); return true; } });
export const heartbeat = mutation({ args: { jobId: v.id("jobs"), workerId: v.string() }, handler: async (ctx, args) => { const job = await ctx.db.get(args.jobId); if (job === null || job.status !== "RUNNING" || job.leaseOwner !== args.workerId) throw new Error("Job lease is not owned by worker"); await ctx.db.patch(args.jobId, { heartbeatAt: Date.now() }); } });
export const complete = mutation({ args: { jobId: v.id("jobs"), workerId: v.string() }, handler: async (ctx, args) => { const job = await ctx.db.get(args.jobId); if (job === null || job.leaseOwner !== args.workerId) throw new Error("Job lease is not owned by worker"); await ctx.db.patch(args.jobId, { status: "COMPLETE", leaseOwner: undefined, leaseExpiresAt: undefined }); } });
export const fail = mutation({ args: { jobId: v.id("jobs"), workerId: v.string(), error: v.string(), retryable: v.boolean() }, handler: async (ctx, args) => { const job = await ctx.db.get(args.jobId); if (job === null || job.leaseOwner !== args.workerId) throw new Error("Job lease is not owned by worker"); const retry = args.retryable && job.attempt < 3; await ctx.db.patch(args.jobId, { status: retry ? "QUEUED" : "FAILED", availableAt: retry ? Date.now() + 2 ** job.attempt * 1_000 : job.availableAt, lastError: args.error, leaseOwner: undefined, leaseExpiresAt: undefined }); } });
export const reclaimExpired = internalMutation({ args: {}, handler: async (ctx) => { const running = await ctx.db.query("jobs").filter((q) => q.eq(q.field("status"), "RUNNING")).collect(); const now = Date.now(); let reclaimed = 0; for (const job of running) if ((job.leaseExpiresAt ?? 0) < now) { await ctx.db.patch(job._id, { status: job.attempt < 3 ? "QUEUED" : "FAILED", availableAt: now, leaseOwner: undefined, leaseExpiresAt: undefined, lastError: "Worker lease expired" }); reclaimed += 1; } return reclaimed; } });
