import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  organizations: defineTable({
    stableId: v.string(),
    name: v.string(),
    createdAt: v.number(),
  }).index("by_stable_id", ["stableId"]),
  projects: defineTable({
    organizationId: v.id("organizations"),
    stableId: v.string(),
    name: v.string(),
    createdAt: v.number(),
  }).index("by_stable_id", ["stableId"]).index("by_organization", ["organizationId"]),
  repositories: defineTable({
    projectId: v.id("projects"),
    stableId: v.string(),
    url: v.optional(v.string()),
    defaultBranch: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_stable_id", ["stableId"]).index("by_project", ["projectId"]),
  uploads: defineTable({
    repositoryId: v.optional(v.id("repositories")),
    storageId: v.id("_storage"),
    fileName: v.string(),
    contentType: v.string(),
    byteLength: v.number(),
    sha256: v.string(),
    createdAt: v.number(),
    expiresAt: v.number(),
  }).index("by_storage_id", ["storageId"]).index("by_expiry", ["expiresAt"]),
  scans: defineTable({
    stableId: v.string(),
    idempotencyKey: v.string(),
    repositoryId: v.string(),
    commitSha: v.string(),
    stage: v.string(),
    attempt: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
    canceledAt: v.optional(v.number()),
    result: v.optional(v.any()),
    error: v.optional(v.string()),
    uploadId: v.optional(v.id("uploads")),
    currentStage: v.optional(v.string()),
    progress: v.optional(v.number()),
    lastHeartbeatAt: v.optional(v.number()),
  }).index("by_stable_id", ["stableId"]).index("by_idempotency", ["idempotencyKey"]),
  scanEvents: defineTable({
    scanId: v.id("scans"),
    sequence: v.number(),
    stage: v.string(),
    at: v.number(),
    message: v.string(),
  }).index("by_scan_sequence", ["scanId", "sequence"]),
  jobs: defineTable({
    scanId: v.id("scans"),
    type: v.string(),
    status: v.string(),
    attempt: v.number(),
    availableAt: v.number(),
    leaseOwner: v.optional(v.string()),
    leaseExpiresAt: v.optional(v.number()),
    heartbeatAt: v.optional(v.number()),
    signature: v.string(),
    lastError: v.optional(v.string()),
    idempotencyKey: v.optional(v.string()),
    engineJobId: v.optional(v.string()),
    requestId: v.optional(v.string()),
    scheduledFunctionId: v.optional(v.id("_scheduled_functions")),
    nextRetryAt: v.optional(v.number()),
    completedAt: v.optional(v.number()),
    canceledAt: v.optional(v.number()),
    dispatchPayload: v.optional(v.any()),
    callbackUrl: v.optional(v.string()),
  }).index("by_status_available", ["status", "availableAt"]).index("by_scan", ["scanId"]),
  jobAttempts: defineTable({
    jobId: v.id("jobs"),
    attempt: v.number(),
    state: v.string(),
    requestId: v.string(),
    startedAt: v.number(),
    completedAt: v.optional(v.number()),
    statusCode: v.optional(v.number()),
    error: v.optional(v.string()),
  }).index("by_job_attempt", ["jobId", "attempt"]),
  jobEvents: defineTable({
    jobId: v.id("jobs"),
    sequence: v.number(),
    state: v.string(),
    message: v.string(),
    at: v.number(),
    traceId: v.string(),
  }).index("by_job_sequence", ["jobId", "sequence"]),
  incidents: defineTable({
    stableId: v.string(),
    packageName: v.string(),
    affectedVersions: v.array(v.string()),
    startsAt: v.optional(v.number()),
    endsAt: v.optional(v.number()),
    createdAt: v.number(),
  }).index("by_stable_id", ["stableId"]),
  aiRuns: defineTable({
    incidentId: v.id("incidents"),
    evidenceHash: v.string(),
    promptVersion: v.string(),
    provider: v.string(),
    status: v.string(),
    latencyMs: v.optional(v.number()),
    evidenceRefs: v.array(v.string()),
    output: v.optional(v.any()),
    error: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_evidence_prompt", ["evidenceHash", "promptVersion"]),
  findingSummaries: defineTable({
    incidentId: v.id("incidents"),
    findingId: v.string(),
    serviceId: v.string(),
    environment: v.string(),
    riskScore: v.number(),
    pathCount: v.number(),
    updatedAt: v.number(),
  }).index("by_incident", ["incidentId"]).index("by_finding", ["findingId"]),
  remediationRuns: defineTable({
    incidentId: v.id("incidents"),
    stableId: v.string(),
    state: v.string(),
    verificationLevel: v.string(),
    remainingPathCount: v.optional(v.number()),
    result: v.optional(v.any()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_stable_id", ["stableId"]).index("by_incident", ["incidentId"]),
  auditEvents: defineTable({
    organizationId: v.optional(v.id("organizations")),
    actor: v.string(),
    action: v.string(),
    targetType: v.string(),
    targetId: v.string(),
    traceId: v.string(),
    metadata: v.optional(v.any()),
    at: v.number(),
  }).index("by_target", ["targetType", "targetId"]).index("by_trace", ["traceId"]),
  engineHeartbeats: defineTable({
    engineId: v.string(),
    traceId: v.string(),
    status: v.string(),
    graphConsistency: v.string(),
    indexerFreshAt: v.optional(v.number()),
    version: v.string(),
    at: v.number(),
  }).index("by_engine", ["engineId"]).index("by_time", ["at"]),
  callbackRequests: defineTable({
    requestId: v.string(),
    receivedAt: v.number(),
    expiresAt: v.number(),
  }).index("by_request_id", ["requestId"]).index("by_expiry", ["expiresAt"]),
});
