/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: fdb658d73a46a8e0c6d5a5cdfe9e1718)
interface __BaseEnv_Env {
	AI: Ai;
	CLOUDFLARE_AI_MODEL: "@cf/openai/gpt-oss-120b";
	NVIDIA_NIM_MODEL: "nvidia/nemotron-3-super-120b-a12b";
	NVIDIA_NIM_BASE_URL: "https://integrate.api.nvidia.com/v1";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CLOUDFLARE_AI_MODEL" | "NVIDIA_NIM_MODEL" | "NVIDIA_NIM_BASE_URL">> {}
}
